In [ ]:
#pip install seaborn 
#pip install scikit-learn

SyntaxError: invalid syntax (1276437672.py, line 2)

In [1]:
#Iris 예측모델
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# 데이터 셋 가져오기
dataset = load_iris()
# 데이터 구분하기 l
X, y = dataset.data, dataset.target
X.shape, y.shape
dataset.target_names
# 판다스로 변환하기.
df = pd.DataFrame(X, columns=dataset.feature_names)
df['target'] = y

#품종명도 추가해보자
df['species'] = df['target'].map(
    {i : name for i, name in enumerate(dataset.target_names)}
    )

sns.pairplot(df, hue='species')
plt.show()



ModuleNotFoundError: No module named 'sklearn'

In [4]:
#간단한 분류 모델 만들기

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

# 데이터를 분할한다.
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, stratify=y,random_state=0)

# 모델을 생성시킨다.
model = RandomForestClassifier()
# 분할된 데이터로 모델을 학습시킨다.
model.fit(X_train,y_train)

# 예측시킨다.
y_pred = model.predict(X_test)

ac = accuracy_score(y_test, y_pred)
ac

0.9666666666666667

Note: you may need to restart the kernel to use updated packages.


In [2]:
#데이터셋 로드
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(X,y,stratify=y,test_size=0.2,random_state=0)

In [1]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

steps = [
    ("scaler", StandardScaler())   # ("단계의 이름", 전처리기 객체)
    , ("svm", SVC(random_state=0)) # ("단계의 이름", 모델 객체)
]

# verbose=True 각단계가 학습하는 과정 log을 출력
pipline = Pipeline(steps, verbose=True) 

print(pipline.steps)

type(pipline.steps)

[('scaler', StandardScaler()), ('svm', SVC(random_state=0))]


list

In [ ]:
# DecisionTree모델 시각화를 통해 과적합원인 확인


In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()
X, y = data.data, data.target
X, y
X_train, X_test,y_train, y_test = train_test_split(X,y,stratify=y,random_state=0)

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

def tree_modeling(X,y,max_depth=None) :
    tree = DecisionTreeClassifier(max_depth=max_depth, random_state=0)
    tree.fit(X,y)
    return tree



In [8]:
# dummy dataset
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "gender":['남성', '여성', '여성', '여성', '여성', '여성', '남성', np.nan],
    "tall":[183.21, 175.73, np.nan, np.nan, 171.18, 181.11, 168.83, 193.99],
    "weight":[82.11, 62.45, 52.21, np.nan, 56.32, 48.93, 63.64, 102.38],
    "blood_type":["B", "B", "O", "AB", "B", np.nan, "B", "A"],
})

df

gender    tall  weight blood_type
0     남성  183.21   82.11          B
1     여성  175.73   62.45          B
2     여성     NaN   52.21          O
3     여성     NaN     NaN         AB
4     여성  171.18   56.32          B
5     여성  181.11   48.93        NaN
6     남성  168.83   63.64          B
7    NaN  193.99  102.38          A

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline

#전처리별로 생성
## 결측치 처리 - 컬럼별로 다르게 처리
## [("전처리기 이름", 전처리기, 리스트[컬럼index또는 이름])] << 튜플형태
na_transformer = ColumnTransformer([
    # 0번이랑 3번 index는 범주형 데이터이기때문에 최빈값으로 결측치를 채운다.
    ("category_imputer", SimpleImputer(strategy="most_frequent"),[0,3])
    # 1번이랑 2번은 평균값으로 결측치를 채운다.
    , ("number_imputer",SimpleImputer(strategy="mean"),[1,2])
])
na_values = na_transformer.fit_transform(df)
na_values



array([['남성', 'B', 183.21, 82.11],
       ['여성', 'B', 175.73, 62.45],
       ['여성', 'O', 179.00833333333335, 52.21],
       ['여성', 'AB', 179.00833333333335, 66.86285714285714],
       ['여성', 'B', 171.18, 56.32],
       ['여성', 'B', 181.11, 48.93],
       ['남성', 'B', 168.83, 63.64],
       ['여성', 'A', 193.99, 102.38]], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline

#전처리별로 생성
## 결측치 처리 - 컬럼별로 다르게 처리
## [("전처리기 이름", 전처리기, 리스트[컬럼index또는 이름])] << 튜플형태
na_transformer = ColumnTransformer([
    # 0번이랑 3번 index는 범주형 데이터이기때문에 최빈값으로 결측치를 채운다.
    ("category_imputer", SimpleImputer(strategy="most_frequent"),[0,3])
    # 1번이랑 2번은 평균값으로 결측치를 채운다.
    #, ("number_imputer",SimpleImputer(strategy="mean"),[1,2])
],
remainder="passthrough"
)
na_values = na_transformer.fit_transform(df)
na_values



array([['남성', 'B', 183.21, 82.11],
       ['여성', 'B', 175.73, 62.45],
       ['여성', 'O', nan, 52.21],
       ['여성', 'AB', nan, nan],
       ['여성', 'B', 171.18, 56.32],
       ['여성', 'B', 181.11, 48.93],
       ['남성', 'B', 168.83, 63.64],
       ['여성', 'A', 193.99, 102.38]], dtype=object)

In [10]:
fe_transformer = ColumnTransformer([
    ("category_ohe", OneHotEncoder(),[0,1])
    , ("number_scalar", StandardScaler(),[2,3])
])

fe_transformer.fit_transform(na_values)


array([[ 1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.5009147 ,  0.86573054],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        , -0.39083666, -0.25056138],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,         nan, -0.83198709],
       [ 0.        ,  1.        ,  0.        ,  1.        ,  0.        ,
         0.        ,         nan,         nan],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        , -0.933279  , -0.59862189],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.2505567 , -1.01822501],
       [ 1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        , -1.21344153, -0.18299336],
       [ 0.        ,  1.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  1.78608579,  2.01665818]])

In [3]:
##암진단을 해보자!## 
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
## 데이터를 가져올때 그냥 data하고 target을나눠서 가져옴
X, y = load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X,y, stratify=y,test_size=0.25,random_state=0)



In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(random_state=0)
gbc.fit(X_train, y_train)


pred_train = gbc.predict(X_train)
pred_test = gbc.predict(X_test)

pred_train_proba = gbc.predict_proba(X_train)[:,1]
pred_test_proba = gbc.predict_proba(X_test)[:,1]